version: '3.9'

networks:
  guacnet:
    driver: bridge

services:

  guacd:
    container_name: guacd
    image: 'docker.io/guacamole/guacd:latest'
    networks:
      - guacnet
    restart: always
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw
    ports:
      - '4822:4822/tcp'

  postgres:
    container_name: postgres
    image: 'docker.io/postgres:latest'
    networks:
      - guacnet
    environment:
        - POSTGRES_USER=guacamole
        - POSTGRES_PASSWORD=guacamole
        - POSTGRES_DB=guacamole_db
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data:z
      - ./init:/docker-entrypoint-initdb.d:Z

  guacamole:
    container_name: guacamole
    depends_on:
      - guacd
      - postgres
    image: 'docker.io/guacamole/guacamole:latest'
    networks:
      - guacnet
    restart: always
    environment:
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_DATABASE=guacamole_db
      - POSTGRES_USER=guacamole
      - POSTGRES_PASSWORD=guacamole
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
    volumes:
      - ./guacamole:/config:z
    ports:
      - '8080:8080/tcp'

  xubuntu:
    container_name: xubuntu
    image: 'accetto/ubuntu-vnc-xfce-firefox-g3'
    networks:
      - guacnet
    restart: always
    environment:
      - VNC_PASSWORD=guacadmin
      - VNC_RESOLUTION=1920x1080
      - VNC_COL_DEPTH=24
      - VNC_PORT=5901
    volumes:
      - ./drive:/home/headless:rw
    ports:
      - '5901:5901/tcp'
      - '6901:6901/tcp'

